# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FnSwitcher < Formula
  desc "Instantly switches keyboard layout when you press the Fn (Globe) key — without the annoying macOS popup."
  homepage "https://github.com/metlenko/fn-switcher"
  version "0.3.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/metlenko/fn-switcher/releases/download/v0.3.1/fn-switcher_0.3.1_darwin_amd64.tar.gz"
    sha256 "dce043e319617b565882e247df1ceec02917471a76fed934968dd2b375254111"

    define_method(:install) do
      app_macos = prefix/"FnSwitcher.app/Contents/MacOS"
      app_macos.mkpath
      app_macos.install "fn-switcher"
      (prefix/"FnSwitcher.app/Contents/Info.plist").write <<~PLIST
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
          <key>CFBundleIdentifier</key>
          <string>com.user.fnswitcher</string>
          <key>CFBundleName</key>
          <string>FnSwitcher</string>
          <key>CFBundleDisplayName</key>
          <string>Fn Switcher</string>
          <key>CFBundleExecutable</key>
          <string>fn-switcher</string>
          <key>CFBundlePackageType</key>
          <string>APPL</string>
          <key>CFBundleVersion</key>
          <string>#{version}</string>
          <key>CFBundleShortVersionString</key>
          <string>#{version}</string>
          <key>CFBundleInfoDictionaryVersion</key>
          <string>6.0</string>
          <key>LSMinimumSystemVersion</key>
          <string>11.0</string>
          <key>LSUIElement</key>
          <true/>
        </dict>
        </plist>
      PLIST
      # Replace the Go linker's ad-hoc "a.out" signature with a proper bundle
      # signature — TCC/System Settings silently refuse linker-signed bundles.
      system "codesign", "--force", "--sign", "-", "--identifier", "com.user.fnswitcher", prefix/"FnSwitcher.app"
      bin.install_symlink prefix/"FnSwitcher.app/Contents/MacOS/fn-switcher"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/metlenko/fn-switcher/releases/download/v0.3.1/fn-switcher_0.3.1_darwin_arm64.tar.gz"
    sha256 "59170d202005f4d452607c1254de891eafba6e3035d4055ef0af67020f8e8038"

    define_method(:install) do
      app_macos = prefix/"FnSwitcher.app/Contents/MacOS"
      app_macos.mkpath
      app_macos.install "fn-switcher"
      (prefix/"FnSwitcher.app/Contents/Info.plist").write <<~PLIST
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
          <key>CFBundleIdentifier</key>
          <string>com.user.fnswitcher</string>
          <key>CFBundleName</key>
          <string>FnSwitcher</string>
          <key>CFBundleDisplayName</key>
          <string>Fn Switcher</string>
          <key>CFBundleExecutable</key>
          <string>fn-switcher</string>
          <key>CFBundlePackageType</key>
          <string>APPL</string>
          <key>CFBundleVersion</key>
          <string>#{version}</string>
          <key>CFBundleShortVersionString</key>
          <string>#{version}</string>
          <key>CFBundleInfoDictionaryVersion</key>
          <string>6.0</string>
          <key>LSMinimumSystemVersion</key>
          <string>11.0</string>
          <key>LSUIElement</key>
          <true/>
        </dict>
        </plist>
      PLIST
      # Replace the Go linker's ad-hoc "a.out" signature with a proper bundle
      # signature — TCC/System Settings silently refuse linker-signed bundles.
      system "codesign", "--force", "--sign", "-", "--identifier", "com.user.fnswitcher", prefix/"FnSwitcher.app"
      bin.install_symlink prefix/"FnSwitcher.app/Contents/MacOS/fn-switcher"
    end
  end

  def caveats
    <<~EOS
      After installing, remove the quarantine attribute:
        sudo xattr -dr com.apple.quarantine #{opt_prefix}/FnSwitcher.app

      fn-switcher requires Accessibility permissions:
        System Settings → Privacy & Security → Accessibility
        Add: #{opt_prefix}/FnSwitcher.app

      To start fn-switcher now and on login:
        brew services start fn-switcher

      To configure layouts and mode, create a config file:
        mkdir -p ~/.config/fn-switcher
        echo '{"layouts": ["ABC", "Russian"]}' > ~/.config/fn-switcher/config.json
    EOS
  end

  service do
    run [opt_prefix/"FnSwitcher.app/Contents/MacOS/fn-switcher"]
    keep_alive true
    log_path var/"log/fn-switcher.log"
    error_log_path var/"log/fn-switcher.error.log"
  end

  test do
    system "#{bin}/fn-switcher", "--version"
  end
end
