# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FnSwitcher < Formula
  desc "Instantly switches keyboard layout when you press the Fn (Globe) key — without the annoying macOS popup."
  homepage "https://github.com/imetlenko/fn-switcher"
  version "0.2.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/imetlenko/fn-switcher/releases/download/v0.2.1/fn-switcher_0.2.1_darwin_amd64.tar.gz"
    sha256 "1db5473bf334def7c89b3d57b706058d8c84ccf5b653e43d9ec3a3e539023f14"

    def install
      bin.install "fn-switcher"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/imetlenko/fn-switcher/releases/download/v0.2.1/fn-switcher_0.2.1_darwin_arm64.tar.gz"
    sha256 "8f219fb8a5e720c73405665f935962fc82b07addbdf9d382d5908fae550252f0"

    def install
      bin.install "fn-switcher"
    end
  end

  def caveats
    <<~EOS
      After installing, remove the quarantine attribute:
        sudo xattr -dr com.apple.quarantine #{opt_bin}/fn-switcher

      fn-switcher requires Accessibility permissions:
        System Settings → Privacy & Security → Accessibility
        Add: #{opt_bin}/fn-switcher

      To start fn-switcher now and on login:
        brew services start fn-switcher

      To configure layouts and mode, create a config file:
        mkdir -p ~/.config/fn-switcher
        echo '{"layouts": ["ABC", "Russian"], "cycle": true}' > ~/.config/fn-switcher/config.json
    EOS
  end

  service do
    run [opt_bin/"fn-switcher"]
    keep_alive true
    log_path var/"log/fn-switcher.log"
    error_log_path var/"log/fn-switcher.error.log"
  end

  test do
    system "#{bin}/fn-switcher", "--version"
  end
end
