# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FnSwitcher < Formula
  desc "Instantly switches keyboard layout when you press the Fn (Globe) key — without the annoying macOS popup."
  homepage "https://github.com/imetlenko/fn-switcher"
  version "0.2.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/imetlenko/fn-switcher/releases/download/v0.2.0/fn-switcher_0.2.0_darwin_amd64.tar.gz"
    sha256 "22408831be3078237d0c8a4c686e4cd4b63a2517d66f131eab6fb216728db8cd"

    def install
      bin.install "fn-switcher"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/imetlenko/fn-switcher/releases/download/v0.2.0/fn-switcher_0.2.0_darwin_arm64.tar.gz"
    sha256 "9e2663cf1af7e1e7600769d1cc1e4ea69a700b19b70fcb5c81cd49c7380dd23e"

    def install
      bin.install "fn-switcher"
    end
  end

  def caveats
    <<~EOS
      After installing, remove the quarantine attribute:
        sudo xattr -dr com.apple.quarantine #{opt_bin}/fn-switcher

      fn-switcher requires Accessibility permissions:
        System Settings → Privacy & Security → Accessibility
        Add: #{opt_bin}/fn-switcher

      To start fn-switcher now and on login:
        brew services start fn-switcher

      To configure layouts and mode, create a config file:
        mkdir -p ~/.config/fn-switcher
        echo '{"layouts": ["ABC", "Russian"], "cycle": true}' > ~/.config/fn-switcher/config.json
    EOS
  end

  service do
    run [opt_bin/"fn-switcher"]
    keep_alive true
    log_path var/"log/fn-switcher.log"
    error_log_path var/"log/fn-switcher.error.log"
  end

  test do
    system "#{bin}/fn-switcher", "--version"
  end
end
